### POST - Add game
POST http://0.0.0.0:8080/games
Content-Type: application/json

{
  "name": "Doom 2",
  "price": "10.00",
  "genre": "FPS"
}

> {%
    client.global.set("game_id", response.body.id);
%}

### GET - get Games List
GET http://0.0.0.0:8080/games
Content-Type: application/json

### GET - get Game with UUID
GET http://0.0.0.0:8080/games/{{game_id}}
Content-Type: application/json